@echo off
echo Starting AI News Chatbot ADK...
echo.
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo.
echo Starting ADK web interface...
python -m google.adk.cli web
echo.
echo Press any key to exit...
pause